### ISSUE TITLE
[Idea] : use DZ "thermostat" device type for the temperature

### ISSUE THREAD

**Issue by rezzalex** [gysmo38/domoticz-python-melcloud#41]
what do you think ?

**Comment by Patricen1** [comment]
> what do you think ?

+1 fully agree! 

https://github.com/gysmo38/domoticz-python-melcloud/issues/39#issuecomment-2078196326

**Comment by rezzalex** [comment]
@Patricen1 ,
I discovered the work was already done by nonolf... after coding it myself,

So please find here the version with all latest modifications (I think) and the thermostat device type working.
Not tested a lot, but it seems to work.

[plugin.zip](https://github.com/gysmo38/domoticz-python-melcloud/files/15236859/plugin.zip)

**Comment by Patricen1** [comment]
Great ! Thanks!

**Comment by janpep** [comment]
Maybe I do not understand it well, but I do not see the expected result. I put this plugin.py in my test environment.
What I see is that the temp setting of my airco's now are stated as 'undefined'.
I expected the setpoint to appear., but It looks they are not created. Am I missing something?

**Comment by rezzalex** [comment]
> Maybe I do not understand it well, but I do not see the expected result. I put this plugin.py in my test environment.
> What I see is that the temp setting of my airco's now are stated as 'undefined'.
> I expected the setpoint to appear., but It looks they are not created. Am I missing something?

Did you remove all other plugin devices ?

**Comment by janpep** [comment]
No none, Why should I remove them all to be recreated? May be because of the existing naming?
Missing a little 'Readme'

**Comment by rezzalex** [comment]
I think I saw in the plugin code that devices are created only if there is none already existing.

**Comment by janpep** [comment]
OK Thank you!
I dd not notice that. I will try and let it know.

**Comment by Patricen1** [comment]
Hello, you should delete the old temp settings multilevel devices and accept new devices.
You'll then have a setpoint device that appears, much more convenient!

**Comment by rezzalex** [comment]
no, in my case, I need to delete EVERY devices ; not only the one I want the plugin to recreate.

**Comment by Patricen1** [comment]
> no, in my case, I need to delete EVERY devices ; not only the one I want the plugin to recreate.

Yes, sorry you are right

**Comment by janpep** [comment]
Indeed. Thank you, When I deleted all, they where recreated.

Disadvantage I see for this solution is that the airco settings are not longer grouped together under the tab 'Switches'.
I have to find it in the 'Utility' tab to adjus the temp.
In fact I had no problem with the level for setting the temp. So it is nice !! that the old setting (commented out) is still there.
For the time being I keep using that. Also because most of the setting are done automatically by script.

FYI: I'm using a four-stage rocket.
1. A wall transmitter can activate a scene (1 push = on, 2 x push = off), for bedroom and livingroom.
2. These scenes, turn a switch device on or off (, which I can of course also operate manually from my dashboard).
3. The switch change triggers a script. (one for bedroom, one for livingroom)
4. These scripts (triggered on the switch, a set time or variable 'day-evening-night') controls whether the air conditioning is turned on or off, on heating or on cooling (based on current temperature), whereby a selected standard temperature for cooling or warming is set.
Usually this is sufficient and I don't have to do anything other than switch it on or off when I want.
- Trigger based on the switch is clear.
- Trigger based on time: When the air conditioning in the bedroom is on, it turns off again in the morning.
- Trigger based on the variable: When I go to bed (variable for night mode is then activated), the script is triggered and the air conditioner in the bedroom turns on if the radiator knob is above a certain temperature. If the air conditioning in the living room is on, it turns off at the same time.

**Comment by Patricen1** [comment]
Hello,
I'm using Aurora theme that groups setpoint and room temp on home screen, very convenient for TRV's , as well as Melcloud.
